name: send webhook on push
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Send-Webhook:
    runs-on: ubuntu-latest
    #if: github.repository_owner == 'The-OpenROAD-Project' && github.ref == 'refs/heads/master'
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: curl -XPOST -u "tspyrou:${{secrets.GITHUBPUBLICREPOTOKEN}}" -H "Accept:application/vnd.github.everest-preview+json" -H "Content-Type:application/json" https://api.github.com/repos/tspyrou/OpenROAD/dispatches --data '{"event_type":"build_application"}'
